[package]
name = "id3handler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
id3 = { git = "https://github.com/polyfloyd/rust-id3" }
chrono = "0.4"
